platform :ios, '9.0'

target 'MultiEducation' do
pod 'PBKits', '~> 1.2.2'
pod 'FCUUID', '~> 1.3.1'
pod 'ZFPlayer', '~> 2.1.6'
pod 'Protobuf', '~> 3.5.0'
pod 'PBService', '~> 4.3.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'BEMCheckBox', '~> 1.4.1'
pod 'YJBannerView', '~> 2.3.8'
pod 'PBBaseClasses', '~> 1.7.1'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'CocoaAsyncSocket', '~> 7.6.3'
pod 'IQKeyboardManager', '~> 5.0.8'
pod 'JKCountDownButton', '~> 1.2.0'
pod 'TTGTagCollectionView', '~> 1.9.0'
pod 'NSURL+QueryDictionary', '~> 1.2.0'
pod 'JVFloatLabeledTextField', '~> 1.2.1'
pod 'WHC_ModelSqliteKit/SQLCipher', '~> 1.3.0'
pod 'libksygpulive/libksygpulive', '~> 3.0.2'
pod 'libksygpulive/KSYGPUResource', '~> 3.0.2'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'TZImagePickerController', '~> 2.0.1'
pod 'Qiniu', '~> 7.2.3'
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'RongCloudIM', '~> 2.8.30'
end
