//
//  MECmdCodes.h
//  MultiEducation
//
//  Created by nanhu on 2018/4/16.
//  Copyright © 2018年 niuduo. All rights reserved.
//

#ifndef MECmdCodes_h
#define MECmdCodes_h

#define FSC_ERROR_POST @"ERROR_POST"//错误:post
#define HEARTBEAT @"HEARTBEAT"//心跳
#define SESSION_POST @"SESSION_POST"//会话:Post
#define FSC_SESSION_LIST @"FSC_SESSION_LIST"//会话:list
#define CMD_FSC_SESSION_PATCH @"FSC_SESSION_PATCH"//会话:patch
#define FSC_SESSION_POST @"FSC_SESSION_POST"//会话:post
#define FSC_SESSION_DELETE @"FSC_SESSION_DELETE"//会话:delete
#define FSC_LINKMAN_LIST @"FSC_LINKMAN_LIST"//获取联系人:list
#define FSC_CLASS_USER_LIST @"FSC_CLASS_USER_LIST"//获取班级用户:list
#define FSC_USER_GET @"FSC_USER_GET"//获取联系人:get
#define FSC_USER_POST @"FSC_USER_POST" //用户:POST
#define FSC_USER_PATCH @"FSC_USER_PATCH"//用户:PATCH
#define FSC_PUBLIC_USER_LIST @"FSC_PUBLIC_USER_LIST"
#define FSC_TEACHER_LIST @"FSC_TEACHER_LIST"//获取老师信息
#define FSC_SCHOOL_USER_LIST @"FSC_SCHOOL_USER_LIST"//获取学校用户:list
#define FSC_DEAN_LIST @"FSC_DEAN_LIST" //获取园务用户

#define SEARCH_USER_LIST @"SEARCH_USER_LIST"//查询用户
#define ADD_LINKMAN_POST @"ADD_LINKMAN_POST"//添加联系人请求
#define ADD_LINKMAN_LIST @"ADD_LINKMAN_LIST"//获取添加联系人请求
#define PERSONAL_INFO_PATCH @"PERSONAL_INFO_PATCH"//修改用户信息
#define SESSION_DEL @"SESSION_DEL"//会话:del
#define PASSWORD_PATCH @"PASSWORD_PATCH" //修改用户密码
#define FSC_LINKMAN_DELETE @"FSC_LINKMAN_DELETE"//删除联系人

#define FSC_CHAT_USER_RECORDER_POST @"FSC_CHAT_USER_RECORDER_POST"//用户聊天纪录:post
#define FSC_CHAT_USER_RECORDER_RESEND @"FSC_CHAT_USER_RECORDER_RESEND"//用户聊天纪录:resend
#define FSC_CHAT_USER_RECORDER_PATCH @"FSC_CHAT_USER_RECORDER_PATCH"//用户聊天记录:patch--撤回

#define FSC_CHAT_GROUP_RECORDER_POST @"FSC_CHAT_GROUP_RECORDER_POST"//群聊纪录:post
#define FSC_CHAT_GROUP_RECORDER_RESEND @"FSC_CHAT_GROUP_RECORDER_RESEND"//群聊聊天纪录:resend
#define FSC_CHAT_GROUP_RECORDER_PATCH @"FSC_CHAT_GROUP_RECORDER_PATCH" //群聊聊天记录:patch--撤回

#define FSC_CHAT_CLASS_RECORDER_POST @"FSC_CHAT_CLASS_RECORDER_POST"//班级聊天纪录:post
#define FSC_CHAT_CLASS_RECORDER_RESEND @"FSC_CHAT_CLASS_RECORDER_RESEND"//班级聊天纪录:resend
#define FSC_CHAT_CLASS_RECORDER_PATCH @"FSC_CHAT_CLASS_RECORDER_PATCH"//班级聊天记录:patch--撤回

#define FSC_CHAT_PUBLIC_RECORDER_POST @"FSC_CHAT_PUBLIC_RECORDER_POST"//公众号聊天记录:post
#define FSC_CHAT_PUBLIC_RECORDER_PATCH @"FSC_CHAT_PUBLIC_RECORDER_PATCH"//公众号聊天记录:patch--撤回
#define FSC_CHAT_PUBLIC_RECORDER_RESEND @"FSC_CHAT_PUBLIC_RECORDER_RESEND"//公众号聊天记录:resend

//添加联系人
#define FSC_USER_GET @"FSC_USER_GET"

#define FSC_NOTIFY_POST @"FSC_NOTIFY_POST"//用户聊天纪录:post
#define FSC_GROUP_SESSION_POST @"FSC_GROUP_SESSION_POST"//群聊session:post
#define FSC_GROUP_SESSION_PATCH @"FSC_GROUP_SESSION_PATCH"//群聊session:patch
#define FSC_GROUP_SESSION_DEL @"FSC_GROUP_SESSION_DEL"//群聊session:delete
#define FSC_GROUP_SESSION_LIST @"FSC_GROUP_SESSION_LIST"
#define FSC_CLASS_LIST @"FSC_CLASS_LIST"//班级:list
#define FSC_BBI_LIST @"FSC_BBI_LIST"//业务基础信息:list

#define FSC_CLASS_SESSION_PATCH @"FSC_CLASS_SESSION_PATCH" //班级聊天状态
#define FSC_CLASS_SESSION_LIST @"FSC_CLASS_SESSION_LIST"

#define FSC_NOTICE_LIST @"FSC_NOTICE_LIST"//通知公告资讯:LIST
#define FSC_ACTIVITY_LIST @"FSC_ACTIVITY_LIST"//活动:LIST
#define FSC_VOTE_LIST @"FSC_VOTE_LIST"//投票:LIST
#define FSC_HOME_ACTIVITY_LIST @"FSC_HOME_ACTIVITY_LIST"

#define FSC_SNS_MSG_LIST @"FSC_SNS_MSG_LIST"//SNS-消息:LIST
#define FSC_SNS_MSG_POST @"FSC_SNS_MSG_POST"//SNS-消息:POST
#define FSC_SNS_MSG_PATCH @"FSC_SNS_MSG_PATCH"//SNS-消息:POST

#define FSC_SNS_POST_FINISH @"FSC_SNS_POST_FINISH"
#define FSC_SNS_SINA_MSG_POST @"FSC_SNS_SINA_MSG_POST"//SNS-消息:PATCH
#define FSC_SNS_SINA_MSG_LIST @"FSC_SNS_SINA_MSG_LIST"//SNS-消息:POST
#define FSC_SNS_MSG_DEL @"FSC_SNS_MSG_DEL"//SNS-消息:DEL
#define FSC_SNS_PRAISE_POST @"FSC_SNS_PRAISE_POST"//SNS-赞:POST
#define FSC_SNS_PRAISE_DEL @"FSC_SNS_PRAISE_DEL"//SNS-赞:DEL
#define FSC_SNS_CMT_POST @"FSC_SNS_CMT_POST"//SNS-评论:POST
#define FSC_SNS_CMT_DEL @"FSC_SNS_CMT_DEL"//SNS-评论:DEL

#define FSC_MSG_LIST @"FSC_MSG_LIST"//消息:LIST
#define FSC_DISK_FILE_LIST @"FSC_DISK_FILE_LIST"//网盘文件:LIST
#define FSC_DISK_FILE_GET @"FSC_DISK_FILE_GET"//网盘文件:GET
#define FSC_DISK_FILE_POST @"FSC_DISK_FILE_POST"//网盘文件:POST
#define FSC_DISK_FILE_PATCH @"FSC_DISK_FILE_PATCH"//网盘文件:PATCH
#define FSC_DISK_FILE_DEL @"FSC_DISK_FILE_DEL"//网盘文件:DEL

#define FSC_QUES_LIST @"FSC_QUES_LIST"//问答社区-问题:LIST
#define FSC_QUES_POST @"FSC_QUES_POST"//问答社区-问题:POST
#define FSC_ANSWER_LIST @"FSC_ANSWER_LIST"//问答社区-回答:LIST
#define FSC_ANSWER_POST @"FSC_ANSWER_POST"//问答社区-回答:POST
#define FSC_ANSWER_DEL @"FSC_ANSWER_DEL"//问答社区-回答:DEL

#define FSC_CLASS_ALBUM_LIST @"FSC_CLASS_ALBUM_LIST"//班级相册:LIST
#define FSC_CLASS_ALBUM_POST @"FSC_CLASS_ALBUM_POST"//班级相册:POST
#define FSC_CLASS_ALBUM_BATCH_POST @"FSC_CLASS_ALBUM_BATCH_POST" //批量上传
#define FSC_CLASS_ALBUM_DEL @"FSC_CLASS_ALBUM_DEL"//班级相册:DEL
#define FSC_CLASS_ALBUM_PATCH @"FSC_CLASS_ALBUM_PATCH"//班级相册:PATCH

#define CODE_GET @"CODE_GET"
#define SESSION_DEL @"SESSION_DEL"
#define FSC_QN_FILE_GET @"FSC_QN_FILE_GET"
#define FSC_ORDER_GET @"FSC_ORDER_GET"
#define FSC_ORDER_PATCH @"FSC_ORDER_PATCH"
#define FSC_ORDER_POST @"FSC_ORDER_POST"

#define FSC_CORDOVA_GET @"FSC_CORDOVA_GET"

#define FSC_CLASS_LIVE_GET @"FSC_CLASS_LIVE_GET"
#define FSC_CLASS_LIVE_PUT @"FSC_CLASS_LIVE_PUT"

#define FSC_MSG_COUNT_GET @"FSC_MSG_COUNT_GET" // 获取find界面未读消息
#define SERVER_LIST @"SERVER_LIST" // 获取find界面未读消息
#define HEARTBEAT @"HEARTBEAT" // 获取find界面未读消息

#endif /* MECmdCodes_h */
