//
//  MEReqCodes.h
//  MultiEducation
//
//  Created by nanhu on 2018/4/16.
//  Copyright © 2018年 niuduo. All rights reserved.
//

#ifndef MEReqCodes_h
#define MEReqCodes_h

#define REQ_GROUP_PORTRAIT_PATCH @"GROUP_PORTRAIT_PATCH"
#define REQ_SESSION_PATCH_READ @"SESSION_PATCH_READ"
#define REQ_SESSION_PATCH_TIMESTAMP @"SESSION_PATCH_TEMESTAMP"

#define REQ_GSESSION_PATCH_AVATAR @"GROUP_PORTRAIT_PATCH"
#define REQ_GSESSION_PATCH_NAME @"GROUP_NAME_PATCH"
#define REQ_GSESSION_PATCH_USERLIST @"GROUP_USER_PATCH"
#define REQ_GSESSION_PATCH_GROUP_STATUS @"GROUP_STATUS_PATCH"

#define REQ_CSESSION_PATCH_CLASS_STATUS @"CLASS_STATUS_PATCH"

//网盘文件上传文件
#define REQ_DISK_FILE_UPLOAD @"DISK_FILE_FILE_UPLOAD"
//网盘文件新建文件夹
#define REQ_DISK_FOLDER_UPLOAD @"DISK_FILE_FOLDER_UPLOAD"

#define REQ_CLASS_ALBUM_FOLDER_UPLOAD @"CLASS_ALBUM_FOLDER_UPLOAD"
#define REQ_CLASS_ALBUM_FILE_UPLOAD @"CLASS_ALBUM_FILE_UPLOAD"

#define REQ_MEMBER_PATCH @"MEMBER_PATCH"


#define LINKMAN_POST_APPLY  1
#define LINKMAN_POST_ACCEPT  2
#define LINKMAN_POST_REJECT  3
#define LINKMAN_POST_DIRECT  4


#define PERSONAL_PORTRAIT_UPDATE @"PERSONAL_PORTRAIT_UPDATE"
#define PERSONAL_USERNAME_UPDATE @"PERSONAL_USERNAME_UPDATE"
#define PERSONAL_NAME_GENDER_UPDATE @"PERSONAL_NAME_GENDER_UPDATE"
#define PERSONAL_MOBILE_UPDATE @"PERSONAL_MOBILE_UPDATE"


#define REQ_USER_POST_REGISTER @"USER_POST_REGISTER"
#define REQ_USER_POST_THIRD_PARTY @"USER_POST_THIRD_PARTY"

#define CLASS_LIVE_HEARTBEAT @"CLASS_LIVE_HEARTBEAT"
#define CLASS_LIVE_POST @"CLASS_LIVE_POST"

#endif /* MEReqCodes_h */
