// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEBabyEvaluate.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GuStudyEvaluateAnswerPb;
@class GuStudyEvaluatePb;
@class GuStudyEvaluateQuesItemPb;
@class GuStudyEvaluateQuesPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MebabyEvaluateRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MebabyEvaluateRoot : GPBRootObject
@end

#pragma mark - GuStudyEvaluateListPb

typedef GPB_ENUM(GuStudyEvaluateListPb_FieldNumber) {
  GuStudyEvaluateListPb_FieldNumber_StudyEvaluatePb = 1,
};

@interface GuStudyEvaluateListPb : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GuStudyEvaluatePb *studyEvaluatePb;
/** Test to see if @c studyEvaluatePb has been set. */
@property(nonatomic, readwrite) BOOL hasStudyEvaluatePb;

@end

#pragma mark - GuStudyEvaluatePb

typedef GPB_ENUM(GuStudyEvaluatePb_FieldNumber) {
  GuStudyEvaluatePb_FieldNumber_Id_p = 1,
  GuStudyEvaluatePb_FieldNumber_GradeId = 2,
  GuStudyEvaluatePb_FieldNumber_Semester = 3,
  GuStudyEvaluatePb_FieldNumber_StudentId = 4,
  GuStudyEvaluatePb_FieldNumber_Month = 5,
  GuStudyEvaluatePb_FieldNumber_Title = 6,
  GuStudyEvaluatePb_FieldNumber_StudyEvaluateQuesPb = 7,
  GuStudyEvaluatePb_FieldNumber_AnswerListPb = 8,
};

@interface GuStudyEvaluatePb : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) int64_t gradeId;

@property(nonatomic, readwrite) int64_t semester;

@property(nonatomic, readwrite) int64_t studentId;

@property(nonatomic, readwrite) int32_t month;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, strong, null_resettable) GuStudyEvaluateQuesPb *studyEvaluateQuesPb;
/** Test to see if @c studyEvaluateQuesPb has been set. */
@property(nonatomic, readwrite) BOOL hasStudyEvaluateQuesPb;

@property(nonatomic, readwrite, strong, null_resettable) GuStudyEvaluateAnswerPb *answerListPb;
/** Test to see if @c answerListPb has been set. */
@property(nonatomic, readwrite) BOOL hasAnswerListPb;

@end

#pragma mark - GuStudyEvaluateQuesPb

typedef GPB_ENUM(GuStudyEvaluateQuesPb_FieldNumber) {
  GuStudyEvaluateQuesPb_FieldNumber_Id_p = 1,
  GuStudyEvaluateQuesPb_FieldNumber_EvaluateId = 2,
  GuStudyEvaluateQuesPb_FieldNumber_Title = 3,
  GuStudyEvaluateQuesPb_FieldNumber_Type = 4,
  GuStudyEvaluateQuesPb_FieldNumber_CheckType = 5,
  GuStudyEvaluateQuesPb_FieldNumber_AnswerPb = 6,
  GuStudyEvaluateQuesPb_FieldNumber_ItemListPb = 7,
};

@interface GuStudyEvaluateQuesPb : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) int64_t evaluateId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** '1在幼儿园2在家里' */
@property(nonatomic, readwrite) int32_t type;

/** '1单选2多选' */
@property(nonatomic, readwrite) int32_t checkType;

@property(nonatomic, readwrite, strong, null_resettable) GuStudyEvaluateAnswerPb *answerPb;
/** Test to see if @c answerPb has been set. */
@property(nonatomic, readwrite) BOOL hasAnswerPb;

@property(nonatomic, readwrite, strong, null_resettable) GuStudyEvaluateQuesItemPb *itemListPb;
/** Test to see if @c itemListPb has been set. */
@property(nonatomic, readwrite) BOOL hasItemListPb;

@end

#pragma mark - GuStudyEvaluateAnswerPb

typedef GPB_ENUM(GuStudyEvaluateAnswerPb_FieldNumber) {
  GuStudyEvaluateAnswerPb_FieldNumber_StudentId = 1,
  GuStudyEvaluateAnswerPb_FieldNumber_EvaluateId = 2,
  GuStudyEvaluateAnswerPb_FieldNumber_QuesId = 3,
  GuStudyEvaluateAnswerPb_FieldNumber_ItemId = 4,
  GuStudyEvaluateAnswerPb_FieldNumber_Answer = 5,
};

@interface GuStudyEvaluateAnswerPb : GPBMessage

@property(nonatomic, readwrite) int64_t studentId;

@property(nonatomic, readwrite) int64_t evaluateId;

@property(nonatomic, readwrite) int64_t quesId;

@property(nonatomic, readwrite) int64_t itemId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *answer;

@end

#pragma mark - GuStudyEvaluateQuesItemPb

typedef GPB_ENUM(GuStudyEvaluateQuesItemPb_FieldNumber) {
  GuStudyEvaluateQuesItemPb_FieldNumber_Id_p = 1,
  GuStudyEvaluateQuesItemPb_FieldNumber_EvaluateId = 2,
  GuStudyEvaluateQuesItemPb_FieldNumber_EvaluateQuesId = 3,
  GuStudyEvaluateQuesItemPb_FieldNumber_Title = 4,
  GuStudyEvaluateQuesItemPb_FieldNumber_CheckCount = 5,
};

@interface GuStudyEvaluateQuesItemPb : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite) int64_t evaluateId;

@property(nonatomic, readwrite) int64_t evaluateQuesId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite) int64_t checkCount;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
