// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEBabyAlbum.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ClassAlbumPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MEUploadStatus

typedef GPB_ENUM(MEUploadStatus) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MEUploadStatus_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 等待中 */
  MEUploadStatus_Waiting = 0,

  /** 正在上传 */
  MEUploadStatus_Uploading = 1,

  /** 上传成功 */
  MEUploadStatus_Success = 2,

  /** 上传失败 */
  MEUploadStatus_Failure = 3,

  /** 已存在 */
  MEUploadStatus_IsExist = 4,
};

GPBEnumDescriptor *MEUploadStatus_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MEUploadStatus_IsValidValue(int32_t value);

#pragma mark - MebabyAlbumRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MebabyAlbumRoot : GPBRootObject
@end

#pragma mark - ClassAlbumListPb

typedef GPB_ENUM(ClassAlbumListPb_FieldNumber) {
  ClassAlbumListPb_FieldNumber_ClassAlbumArray = 1,
};

@interface ClassAlbumListPb : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<ClassAlbumPb*> *classAlbumArray;
/** The number of items in @c classAlbumArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classAlbumArray_Count;

@end

#pragma mark - ClassAlbumPb

typedef GPB_ENUM(ClassAlbumPb_FieldNumber) {
  ClassAlbumPb_FieldNumber_Id_p = 1,
  ClassAlbumPb_FieldNumber_ClassId = 2,
  ClassAlbumPb_FieldNumber_IsParent = 3,
  ClassAlbumPb_FieldNumber_ParentId = 4,
  ClassAlbumPb_FieldNumber_FileId = 5,
  ClassAlbumPb_FieldNumber_FileName = 6,
  ClassAlbumPb_FieldNumber_FileType = 7,
  ClassAlbumPb_FieldNumber_FileSize = 8,
  ClassAlbumPb_FieldNumber_FilePath = 9,
  ClassAlbumPb_FieldNumber_DataStatus = 10,
  ClassAlbumPb_FieldNumber_CreatedDate = 11,
  ClassAlbumPb_FieldNumber_ModifiedDate = 12,
  ClassAlbumPb_FieldNumber_Md5 = 13,
  ClassAlbumPb_FieldNumber_UpPercent = 14,
  ClassAlbumPb_FieldNumber_IsExist = 15,
  ClassAlbumPb_FieldNumber_FormatterDate = 16,
  ClassAlbumPb_FieldNumber_FileData = 17,
  ClassAlbumPb_FieldNumber_UploadStatu = 18,
  ClassAlbumPb_FieldNumber_IsSelect = 19,
  ClassAlbumPb_FieldNumber_IsSelectStatus = 20,
  ClassAlbumPb_FieldNumber_TotalPortrait = 21,
  ClassAlbumPb_FieldNumber_CoverImageData = 22,
};

@interface ClassAlbumPb : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

/** 班级id */
@property(nonatomic, readwrite) int64_t classId;

/** 是否为父节点1是0否 */
@property(nonatomic, readwrite) int32_t isParent;

/** 父节点id */
@property(nonatomic, readwrite) int64_t parentId;

/** 节点id */
@property(nonatomic, readwrite) int64_t fileId;

/** 文件名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileName;

/** 文件类型值 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fileType;

/** 文件大小单位字节 */
@property(nonatomic, readwrite) int64_t fileSize;

/** 文件路径 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *filePath;

/** 数据状态 */
@property(nonatomic, readwrite) int32_t dataStatus;

@property(nonatomic, readwrite) int64_t createdDate;

@property(nonatomic, readwrite) int64_t modifiedDate;

/** 文件md5 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *md5;

/** 上传进度 */
@property(nonatomic, readwrite) int32_t upPercent;

/** 是否已经存在 1存在0不存在 */
@property(nonatomic, readwrite) int32_t isExist;

/** 格式化日期 yyyy-MM */
@property(nonatomic, readwrite, copy, null_resettable) NSString *formatterDate;

/** data */
@property(nonatomic, readwrite, copy, null_resettable) NSData *fileData;

/** 上传状态 */
@property(nonatomic, readwrite) MEUploadStatus uploadStatu;

/**  是否处于选中状态，用于delete情况 */
@property(nonatomic, readwrite) int32_t isSelect;

/** 是否处于要选择状态 */
@property(nonatomic, readwrite) int32_t isSelectStatus;

/** bucketDomain + portrait */
@property(nonatomic, readwrite, copy, null_resettable) NSString *totalPortrait;

/** 封面图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *coverImageData;

@end

/**
 * Fetches the raw value of a @c ClassAlbumPb's @c uploadStatu property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ClassAlbumPb_UploadStatu_RawValue(ClassAlbumPb *message);
/**
 * Sets the raw value of an @c ClassAlbumPb's @c uploadStatu property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetClassAlbumPb_UploadStatu_RawValue(ClassAlbumPb *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
