// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEBabyIndex.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MebabyIndex.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MebabyIndexRoot

@implementation MebabyIndexRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MebabyIndexRoot_FileDescriptor

static GPBFileDescriptor *MebabyIndexRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GuIndexPb

@implementation GuIndexPb

@dynamic studentId;
@dynamic hasStudentArchives, studentArchives;
@dynamic hasStudyEvaluate, studyEvaluate;

typedef struct GuIndexPb__storage_ {
  uint32_t _has_storage_[1];
  GuStudentArchivesPb *studentArchives;
  GuStudyEvaluatePb *studyEvaluate;
  int64_t studentId;
} GuIndexPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "studentId",
        .dataTypeSpecific.className = NULL,
        .number = GuIndexPb_FieldNumber_StudentId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuIndexPb__storage_, studentId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "studentArchives",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudentArchivesPb),
        .number = GuIndexPb_FieldNumber_StudentArchives,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuIndexPb__storage_, studentArchives),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "studyEvaluate",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluatePb),
        .number = GuIndexPb_FieldNumber_StudyEvaluate,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuIndexPb__storage_, studyEvaluate),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuIndexPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuIndexPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\t\000\002\017\000\003\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudentArchivesListPb

@implementation GuStudentArchivesListPb

@dynamic hasStudentArchivesPb, studentArchivesPb;

typedef struct GuStudentArchivesListPb__storage_ {
  uint32_t _has_storage_[1];
  GuStudentArchivesPb *studentArchivesPb;
} GuStudentArchivesListPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "studentArchivesPb",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudentArchivesPb),
        .number = GuStudentArchivesListPb_FieldNumber_StudentArchivesPb,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudentArchivesListPb__storage_, studentArchivesPb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudentArchivesListPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudentArchivesListPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\021\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudentArchivesPb

@implementation GuStudentArchivesPb

@dynamic title;
@dynamic studentId;
@dynamic gradeId;
@dynamic semester;
@dynamic petName;
@dynamic gender;
@dynamic birthday;
@dynamic age;
@dynamic zodiac;
@dynamic height;
@dynamic weight;
@dynamic leftVision;
@dynamic rightVision;
@dynamic bloodType;
@dynamic hemoglobin;
@dynamic nation;
@dynamic homeAddress;
@dynamic contactNumber;
@dynamic warnItem;
@dynamic motherName;
@dynamic motherMobile;
@dynamic motherWorkUnit;
@dynamic fatherName;
@dynamic fatherMobile;
@dynamic fatherWorkUnit;
@dynamic studentPortrait;

typedef struct GuStudentArchivesPb__storage_ {
  uint32_t _has_storage_[1];
  int32_t semester;
  int32_t gender;
  int32_t age;
  int32_t height;
  int32_t weight;
  int32_t hemoglobin;
  NSString *petName;
  NSString *zodiac;
  NSString *leftVision;
  NSString *rightVision;
  NSString *bloodType;
  NSString *nation;
  NSString *homeAddress;
  NSString *contactNumber;
  NSString *warnItem;
  NSString *motherName;
  NSString *motherMobile;
  NSString *motherWorkUnit;
  NSString *fatherName;
  NSString *fatherMobile;
  NSString *fatherWorkUnit;
  NSString *studentPortrait;
  int64_t title;
  int64_t studentId;
  int64_t gradeId;
  int64_t birthday;
} GuStudentArchivesPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Title,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "studentId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_StudentId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, studentId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "gradeId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_GradeId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, gradeId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "semester",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Semester,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, semester),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "petName",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_PetName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, petName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "gender",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Gender,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, gender),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "birthday",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Birthday,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, birthday),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "age",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Age,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, age),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "zodiac",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Zodiac,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, zodiac),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "height",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Height,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, height),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "weight",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Weight,
        .hasIndex = 10,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, weight),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "leftVision",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_LeftVision,
        .hasIndex = 11,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, leftVision),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "rightVision",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_RightVision,
        .hasIndex = 12,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, rightVision),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "bloodType",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_BloodType,
        .hasIndex = 13,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, bloodType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "hemoglobin",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Hemoglobin,
        .hasIndex = 14,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, hemoglobin),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "nation",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_Nation,
        .hasIndex = 15,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, nation),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "homeAddress",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_HomeAddress,
        .hasIndex = 16,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, homeAddress),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contactNumber",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_ContactNumber,
        .hasIndex = 17,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, contactNumber),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "warnItem",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_WarnItem,
        .hasIndex = 18,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, warnItem),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "motherName",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_MotherName,
        .hasIndex = 19,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, motherName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "motherMobile",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_MotherMobile,
        .hasIndex = 20,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, motherMobile),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "motherWorkUnit",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_MotherWorkUnit,
        .hasIndex = 21,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, motherWorkUnit),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fatherName",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_FatherName,
        .hasIndex = 22,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, fatherName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fatherMobile",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_FatherMobile,
        .hasIndex = 23,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, fatherMobile),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "fatherWorkUnit",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_FatherWorkUnit,
        .hasIndex = 24,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, fatherWorkUnit),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "studentPortrait",
        .dataTypeSpecific.className = NULL,
        .number = GuStudentArchivesPb_FieldNumber_StudentPortrait,
        .hasIndex = 25,
        .offset = (uint32_t)offsetof(GuStudentArchivesPb__storage_, studentPortrait),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudentArchivesPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudentArchivesPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\020\002\t\000\003\007\000\005\007\000\014\n\000\r\013\000\016\t\000\021\013\000\022\r\000\023\010\000\024\n\000\025\014\000\026\016\000\027\n\000"
        "\030\014\000\031\016\000\032\017\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudyEvaluateListPb

@implementation GuStudyEvaluateListPb

@dynamic hasStudyEvaluatePb, studyEvaluatePb;

typedef struct GuStudyEvaluateListPb__storage_ {
  uint32_t _has_storage_[1];
  GuStudyEvaluatePb *studyEvaluatePb;
} GuStudyEvaluateListPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "studyEvaluatePb",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluatePb),
        .number = GuStudyEvaluateListPb_FieldNumber_StudyEvaluatePb,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudyEvaluateListPb__storage_, studyEvaluatePb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudyEvaluateListPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudyEvaluateListPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\017\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudyEvaluatePb

@implementation GuStudyEvaluatePb

@dynamic id_p;
@dynamic gradeId;
@dynamic semester;
@dynamic studentId;
@dynamic month;
@dynamic title;
@dynamic hasStudyEvaluateQuesPb, studyEvaluateQuesPb;
@dynamic hasAnswerListPb, answerListPb;

typedef struct GuStudyEvaluatePb__storage_ {
  uint32_t _has_storage_[1];
  int32_t month;
  NSString *title;
  GuStudyEvaluateQuesPb *studyEvaluateQuesPb;
  GuStudyEvaluateAnswerPb *answerListPb;
  int64_t id_p;
  int64_t gradeId;
  int64_t semester;
  int64_t studentId;
} GuStudyEvaluatePb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluatePb_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "gradeId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluatePb_FieldNumber_GradeId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, gradeId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "semester",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluatePb_FieldNumber_Semester,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, semester),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "studentId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluatePb_FieldNumber_StudentId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, studentId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "month",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluatePb_FieldNumber_Month,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, month),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluatePb_FieldNumber_Title,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "studyEvaluateQuesPb",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluateQuesPb),
        .number = GuStudyEvaluatePb_FieldNumber_StudyEvaluateQuesPb,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, studyEvaluateQuesPb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "answerListPb",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluateAnswerPb),
        .number = GuStudyEvaluatePb_FieldNumber_AnswerListPb,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(GuStudyEvaluatePb__storage_, answerListPb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudyEvaluatePb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudyEvaluatePb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002\007\000\004\t\000\007\023\000\010\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudyEvaluateQuesPb

@implementation GuStudyEvaluateQuesPb

@dynamic id_p;
@dynamic evaluateId;
@dynamic title;
@dynamic type;
@dynamic checkType;
@dynamic hasAnswerPb, answerPb;
@dynamic hasItemListPb, itemListPb;

typedef struct GuStudyEvaluateQuesPb__storage_ {
  uint32_t _has_storage_[1];
  int32_t type;
  int32_t checkType;
  NSString *title;
  GuStudyEvaluateAnswerPb *answerPb;
  GuStudyEvaluateQuesItemPb *itemListPb;
  int64_t id_p;
  int64_t evaluateId;
} GuStudyEvaluateQuesPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesPb_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "evaluateId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesPb_FieldNumber_EvaluateId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, evaluateId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesPb_FieldNumber_Title,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesPb_FieldNumber_Type,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, type),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "checkType",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesPb_FieldNumber_CheckType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, checkType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "answerPb",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluateAnswerPb),
        .number = GuStudyEvaluateQuesPb_FieldNumber_AnswerPb,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, answerPb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "itemListPb",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluateQuesItemPb),
        .number = GuStudyEvaluateQuesPb_FieldNumber_ItemListPb,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesPb__storage_, itemListPb),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudyEvaluateQuesPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudyEvaluateQuesPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002\n\000\005\t\000\006\010\000\007\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudyEvaluateAnswerPb

@implementation GuStudyEvaluateAnswerPb

@dynamic studentId;
@dynamic evaluateId;
@dynamic quesId;
@dynamic itemId;
@dynamic answer;

typedef struct GuStudyEvaluateAnswerPb__storage_ {
  uint32_t _has_storage_[1];
  NSString *answer;
  int64_t studentId;
  int64_t evaluateId;
  int64_t quesId;
  int64_t itemId;
} GuStudyEvaluateAnswerPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "studentId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateAnswerPb_FieldNumber_StudentId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudyEvaluateAnswerPb__storage_, studentId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "evaluateId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateAnswerPb_FieldNumber_EvaluateId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuStudyEvaluateAnswerPb__storage_, evaluateId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "quesId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateAnswerPb_FieldNumber_QuesId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuStudyEvaluateAnswerPb__storage_, quesId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "itemId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateAnswerPb_FieldNumber_ItemId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GuStudyEvaluateAnswerPb__storage_, itemId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "answer",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateAnswerPb_FieldNumber_Answer,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GuStudyEvaluateAnswerPb__storage_, answer),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudyEvaluateAnswerPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudyEvaluateAnswerPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\001\t\000\002\n\000\003\006\000\004\006\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GuStudyEvaluateQuesItemPb

@implementation GuStudyEvaluateQuesItemPb

@dynamic id_p;
@dynamic evaluateId;
@dynamic evaluateQuesId;
@dynamic title;
@dynamic checkCount;

typedef struct GuStudyEvaluateQuesItemPb__storage_ {
  uint32_t _has_storage_[1];
  NSString *title;
  int64_t id_p;
  int64_t evaluateId;
  int64_t evaluateQuesId;
  int64_t checkCount;
} GuStudyEvaluateQuesItemPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesItemPb_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesItemPb__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "evaluateId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesItemPb_FieldNumber_EvaluateId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesItemPb__storage_, evaluateId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "evaluateQuesId",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesItemPb_FieldNumber_EvaluateQuesId,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesItemPb__storage_, evaluateQuesId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "title",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesItemPb_FieldNumber_Title,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesItemPb__storage_, title),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "checkCount",
        .dataTypeSpecific.className = NULL,
        .number = GuStudyEvaluateQuesItemPb_FieldNumber_CheckCount,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GuStudyEvaluateQuesItemPb__storage_, checkCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuStudyEvaluateQuesItemPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuStudyEvaluateQuesItemPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\002\n\000\003\016\000\005\n\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
