// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEBabyIndex.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MebabyIndex.pbobjc.h"
 #import "MebabyEvaluate.pbobjc.h"
 #import "MebabyGrowth.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MebabyIndexRoot

@implementation MebabyIndexRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MebabyIndexRoot_FileDescriptor

static GPBFileDescriptor *MebabyIndexRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GuIndexPb

@implementation GuIndexPb

@dynamic studentId;
@dynamic hasStudentArchives, studentArchives;
@dynamic hasStudyEvaluate, studyEvaluate;

typedef struct GuIndexPb__storage_ {
  uint32_t _has_storage_[1];
  GuStudentArchivesPb *studentArchives;
  GuStudyEvaluatePb *studyEvaluate;
  int64_t studentId;
} GuIndexPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "studentId",
        .dataTypeSpecific.className = NULL,
        .number = GuIndexPb_FieldNumber_StudentId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GuIndexPb__storage_, studentId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "studentArchives",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudentArchivesPb),
        .number = GuIndexPb_FieldNumber_StudentArchives,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GuIndexPb__storage_, studentArchives),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "studyEvaluate",
        .dataTypeSpecific.className = GPBStringifySymbol(GuStudyEvaluatePb),
        .number = GuIndexPb_FieldNumber_StudyEvaluate,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GuIndexPb__storage_, studyEvaluate),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GuIndexPb class]
                                     rootClass:[MebabyIndexRoot class]
                                          file:MebabyIndexRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GuIndexPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\t\000\002\017\000\003\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
