// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEBabyGrowth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GuStudentArchivesPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MebabyGrowthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MebabyGrowthRoot : GPBRootObject
@end

#pragma mark - GuStudentArchivesListPb

typedef GPB_ENUM(GuStudentArchivesListPb_FieldNumber) {
  GuStudentArchivesListPb_FieldNumber_StudentArchivesPbArray = 1,
};

@interface GuStudentArchivesListPb : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GuStudentArchivesPb*> *studentArchivesPbArray;
/** The number of items in @c studentArchivesPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger studentArchivesPbArray_Count;

@end

#pragma mark - GuStudentArchivesPb

typedef GPB_ENUM(GuStudentArchivesPb_FieldNumber) {
  GuStudentArchivesPb_FieldNumber_Title = 1,
  GuStudentArchivesPb_FieldNumber_StudentId = 2,
  GuStudentArchivesPb_FieldNumber_GradeId = 3,
  GuStudentArchivesPb_FieldNumber_Semester = 4,
  GuStudentArchivesPb_FieldNumber_PetName = 5,
  GuStudentArchivesPb_FieldNumber_Gender = 6,
  GuStudentArchivesPb_FieldNumber_Birthday = 7,
  GuStudentArchivesPb_FieldNumber_Age = 8,
  GuStudentArchivesPb_FieldNumber_Zodiac = 9,
  GuStudentArchivesPb_FieldNumber_Height = 10,
  GuStudentArchivesPb_FieldNumber_Weight = 11,
  GuStudentArchivesPb_FieldNumber_LeftVision = 12,
  GuStudentArchivesPb_FieldNumber_RightVision = 13,
  GuStudentArchivesPb_FieldNumber_BloodType = 14,
  GuStudentArchivesPb_FieldNumber_Hemoglobin = 15,
  GuStudentArchivesPb_FieldNumber_Nation = 16,
  GuStudentArchivesPb_FieldNumber_HomeAddress = 17,
  GuStudentArchivesPb_FieldNumber_ContactNumber = 18,
  GuStudentArchivesPb_FieldNumber_WarnItem = 19,
  GuStudentArchivesPb_FieldNumber_MotherName = 20,
  GuStudentArchivesPb_FieldNumber_MotherMobile = 21,
  GuStudentArchivesPb_FieldNumber_MotherWorkUnit = 22,
  GuStudentArchivesPb_FieldNumber_FatherName = 23,
  GuStudentArchivesPb_FieldNumber_FatherMobile = 24,
  GuStudentArchivesPb_FieldNumber_FatherWorkUnit = 25,
  GuStudentArchivesPb_FieldNumber_StudentPortrait = 26,
};

@interface GuStudentArchivesPb : GPBMessage

@property(nonatomic, readwrite) int64_t title;

@property(nonatomic, readwrite) int64_t studentId;

@property(nonatomic, readwrite) int64_t gradeId;

@property(nonatomic, readwrite) int32_t semester;

/** 小名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *petName;

/** 性别 */
@property(nonatomic, readwrite) int32_t gender;

/** 出生年月 */
@property(nonatomic, readwrite) int64_t birthday;

/** 年龄 */
@property(nonatomic, readwrite) int32_t age;

/** 生肖 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *zodiac;

/** 身高 */
@property(nonatomic, readwrite) int32_t height;

/** 体重 */
@property(nonatomic, readwrite) int32_t weight;

/** 左眼视力 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *leftVision;

/** 右眼视力 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rightVision;

/** 血型 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bloodType;

/** 血色素 */
@property(nonatomic, readwrite) int32_t hemoglobin;

/** 民族 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nation;

/** 家庭住址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *homeAddress;

/** 联系电话 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *contactNumber;

/** 注意事项 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *warnItem;

/** 妈妈姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *motherName;

/** 妈妈手机号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *motherMobile;

/** 妈妈工作单位 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *motherWorkUnit;

/** 父亲姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fatherName;

/** 父亲手机号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fatherMobile;

/** 父亲工作单位 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *fatherWorkUnit;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *studentPortrait;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
