// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEClass.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MEPBClass;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MeclassRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeclassRoot : GPBRootObject
@end

#pragma mark - MEPBClassList

typedef GPB_ENUM(MEPBClassList_FieldNumber) {
  MEPBClassList_FieldNumber_ClassPbArray = 1,
};

@interface MEPBClassList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEPBClass*> *classPbArray;
/** The number of items in @c classPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classPbArray_Count;

@end

#pragma mark - MEPBClass

typedef GPB_ENUM(MEPBClass_FieldNumber) {
  MEPBClass_FieldNumber_Id_p = 1,
  MEPBClass_FieldNumber_ClassName = 2,
  MEPBClass_FieldNumber_GradeId = 3,
  MEPBClass_FieldNumber_GradeName = 4,
  MEPBClass_FieldNumber_MonitorURL = 5,
  MEPBClass_FieldNumber_Year = 6,
  MEPBClass_FieldNumber_Semester = 7,
};

@interface MEPBClass : GPBMessage

/** id */
@property(nonatomic, readwrite) int64_t id_p;

/** 班级名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *className;

/** 年级id */
@property(nonatomic, readwrite) int64_t gradeId;

/** 年级名次 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *gradeName;

/** 监控地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *monitorURL;

/** 年 */
@property(nonatomic, readwrite) int64_t year;

/** 学期 */
@property(nonatomic, readwrite) int32_t semester;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
