// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEClassLive.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MEPBClassLive;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MeclassLiveRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeclassLiveRoot : GPBRootObject
@end

#pragma mark - MEPBClassLive

typedef GPB_ENUM(MEPBClassLive_FieldNumber) {
  MEPBClassLive_FieldNumber_Id_p = 1,
  MEPBClassLive_FieldNumber_TeacherId = 2,
  MEPBClassLive_FieldNumber_ClassId = 3,
  MEPBClassLive_FieldNumber_StreamURL = 4,
  MEPBClassLive_FieldNumber_Status = 5,
  MEPBClassLive_FieldNumber_VideoURL = 6,
  MEPBClassLive_FieldNumber_RecorderListArray = 7,
  MEPBClassLive_FieldNumber_Title = 8,
  MEPBClassLive_FieldNumber_CoverImg = 9,
};

@interface MEPBClassLive : GPBMessage

/** ID */
@property(nonatomic, readwrite) int64_t id_p;

/** 直播老师ID */
@property(nonatomic, readwrite) int64_t teacherId;

/** 班级ID 必传 */
@property(nonatomic, readwrite) int64_t classId;

/** 直播流 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *streamURL;

/** 直播状态0未开始 1直播中 */
@property(nonatomic, readwrite) int32_t status;

/** 往期视频uri */
@property(nonatomic, readwrite, copy, null_resettable) NSString *videoURL;

/** 往期视频 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEPBClassLive*> *recorderListArray;
/** The number of items in @c recorderListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger recorderListArray_Count;

/** 视频标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 占位placeholder */
@property(nonatomic, readwrite, copy, null_resettable) NSString *coverImg;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
