// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEClassMember.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MEClassMember;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MeclassMemberRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeclassMemberRoot : GPBRootObject
@end

#pragma mark - MEClassMember

typedef GPB_ENUM(MEClassMember_FieldNumber) {
  MEClassMember_FieldNumber_Id_p = 1,
  MEClassMember_FieldNumber_ClassId = 2,
  MEClassMember_FieldNumber_Name = 3,
  MEClassMember_FieldNumber_Portrait = 4,
  MEClassMember_FieldNumber_UserType = 5,
  MEClassMember_FieldNumber_Gender = 6,
  MEClassMember_FieldNumber_SchoolName = 7,
  MEClassMember_FieldNumber_Status = 8,
  MEClassMember_FieldNumber_Timestamp = 9,
  MEClassMember_FieldNumber_StudentName = 10,
  MEClassMember_FieldNumber_OwnerId = 11,
  MEClassMember_FieldNumber_IndexAscii = 12,
};

@interface MEClassMember : GPBMessage

/** 联系人id */
@property(nonatomic, readwrite) int64_t id_p;

/** 班级id */
@property(nonatomic, readwrite) int64_t classId;

/** 中文名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

/** 用户类型 */
@property(nonatomic, readwrite) int32_t userType;

/** 性别 */
@property(nonatomic, readwrite) int32_t gender;

/** 学校名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *schoolName;

/** 1正常 0期间离开 */
@property(nonatomic, readwrite) int32_t status;

/** 创建时间戳 拉取列表时取此字段最大值 */
@property(nonatomic, readwrite) int64_t timestamp;

/** 学生名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *studentName;

/** 成员所属用户ID */
@property(nonatomic, readwrite) int64_t ownerId;

/** 名字首字母 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *indexAscii;

@end

#pragma mark - MEClassMemberList

typedef GPB_ENUM(MEClassMemberList_FieldNumber) {
  MEClassMemberList_FieldNumber_ClassUserArray = 1,
  MEClassMemberList_FieldNumber_ClassIds = 2,
  MEClassMemberList_FieldNumber_Timestamp = 3,
};

@interface MEClassMemberList : GPBMessage

/** 班级用户列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEClassMember*> *classUserArray;
/** The number of items in @c classUserArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classUserArray_Count;

/** 班级ids 不传则返回所有 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *classIds;

/** 上次更新时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
