// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MECordova.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MecordovaRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MecordovaRoot : GPBRootObject
@end

#pragma mark - MEPBCordova

typedef GPB_ENUM(MEPBCordova_FieldNumber) {
  MEPBCordova_FieldNumber_Version = 1,
  MEPBCordova_FieldNumber_AndroidKey = 2,
  MEPBCordova_FieldNumber_IosKey = 3,
  MEPBCordova_FieldNumber_CreatedDate = 4,
  MEPBCordova_FieldNumber_BucketDomain = 5,
};

@interface MEPBCordova : GPBMessage

/** 资源包版本 */
@property(nonatomic, readwrite) int64_t version;

/** 安卓key */
@property(nonatomic, readwrite, copy, null_resettable) NSString *androidKey;

/** iOSkey */
@property(nonatomic, readwrite, copy, null_resettable) NSString *iosKey;

/** 创建更新日期 */
@property(nonatomic, readwrite) int64_t createdDate;

/** 下载资源uri */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bucketDomain;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
