// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MECordova.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Mecordova.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MecordovaRoot

@implementation MecordovaRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MecordovaRoot_FileDescriptor

static GPBFileDescriptor *MecordovaRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MEPBCordova

@implementation MEPBCordova

@dynamic version;
@dynamic androidKey;
@dynamic iosKey;
@dynamic createdDate;
@dynamic bucketDomain;

typedef struct MEPBCordova__storage_ {
  uint32_t _has_storage_[1];
  NSString *androidKey;
  NSString *iosKey;
  NSString *bucketDomain;
  int64_t version;
  int64_t createdDate;
} MEPBCordova__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "version",
        .dataTypeSpecific.className = NULL,
        .number = MEPBCordova_FieldNumber_Version,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MEPBCordova__storage_, version),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "androidKey",
        .dataTypeSpecific.className = NULL,
        .number = MEPBCordova_FieldNumber_AndroidKey,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MEPBCordova__storage_, androidKey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "iosKey",
        .dataTypeSpecific.className = NULL,
        .number = MEPBCordova_FieldNumber_IosKey,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MEPBCordova__storage_, iosKey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "createdDate",
        .dataTypeSpecific.className = NULL,
        .number = MEPBCordova_FieldNumber_CreatedDate,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MEPBCordova__storage_, createdDate),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "bucketDomain",
        .dataTypeSpecific.className = NULL,
        .number = MEPBCordova_FieldNumber_BucketDomain,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MEPBCordova__storage_, bucketDomain),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MEPBCordova class]
                                     rootClass:[MecordovaRoot class]
                                          file:MecordovaRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MEPBCordova__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\004\002\n\000\003\006\000\004\013\000\005\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
