// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEForwardEvaluate.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MeforwardEvaluate.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MeforwardEvaluateRoot

@implementation MeforwardEvaluateRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MeforwardEvaluateRoot_FileDescriptor

static GPBFileDescriptor *MeforwardEvaluateRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Month

@implementation Month

@dynamic month;
@dynamic name;

typedef struct Month__storage_ {
  uint32_t _has_storage_[1];
  int32_t month;
  NSString *name;
} Month__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "month",
        .dataTypeSpecific.className = NULL,
        .number = Month_FieldNumber_Month,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Month__storage_, month),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = Month_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Month__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Month class]
                                     rootClass:[MeforwardEvaluateRoot class]
                                          file:MeforwardEvaluateRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Month__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ForwardEvaluate

@implementation ForwardEvaluate

@dynamic id_p;
@dynamic gradeId;
@dynamic semester;
@dynamic name;
@dynamic monthsArray, monthsArray_Count;

typedef struct ForwardEvaluate__storage_ {
  uint32_t _has_storage_[1];
  int32_t semester;
  NSString *name;
  NSMutableArray *monthsArray;
  int64_t id_p;
  int64_t gradeId;
} ForwardEvaluate__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = ForwardEvaluate_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ForwardEvaluate__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "gradeId",
        .dataTypeSpecific.className = NULL,
        .number = ForwardEvaluate_FieldNumber_GradeId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ForwardEvaluate__storage_, gradeId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "semester",
        .dataTypeSpecific.className = NULL,
        .number = ForwardEvaluate_FieldNumber_Semester,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ForwardEvaluate__storage_, semester),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = ForwardEvaluate_FieldNumber_Name,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ForwardEvaluate__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "monthsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Month),
        .number = ForwardEvaluate_FieldNumber_MonthsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ForwardEvaluate__storage_, monthsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ForwardEvaluate class]
                                     rootClass:[MeforwardEvaluateRoot class]
                                          file:MeforwardEvaluateRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ForwardEvaluate__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\007\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - ForwardEvaluateList

@implementation ForwardEvaluateList

@dynamic listArray, listArray_Count;

typedef struct ForwardEvaluateList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *listArray;
} ForwardEvaluateList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "listArray",
        .dataTypeSpecific.className = GPBStringifySymbol(ForwardEvaluate),
        .number = ForwardEvaluateList_FieldNumber_ListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(ForwardEvaluateList__storage_, listArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ForwardEvaluateList class]
                                     rootClass:[MeforwardEvaluateRoot class]
                                          file:MeforwardEvaluateRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ForwardEvaluateList__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
