// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEGradeList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MEGrade;
@class MESemester;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MegradeListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MegradeListRoot : GPBRootObject
@end

#pragma mark - MESemester

typedef GPB_ENUM(MESemester_FieldNumber) {
  MESemester_FieldNumber_Semester = 1,
  MESemester_FieldNumber_Name = 2,
};

@interface MESemester : GPBMessage

/** 学期 */
@property(nonatomic, readwrite) int32_t semester;

/** 学期名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - MEGrade

typedef GPB_ENUM(MEGrade_FieldNumber) {
  MEGrade_FieldNumber_GradeId = 1,
  MEGrade_FieldNumber_Semester = 2,
  MEGrade_FieldNumber_Name = 3,
  MEGrade_FieldNumber_SListArray = 4,
};

@interface MEGrade : GPBMessage

/** 年级ID */
@property(nonatomic, readwrite) int64_t gradeId;

/** 学期 用户查询 */
@property(nonatomic, readwrite) int32_t semester;

/** 年级名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 学期列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MESemester*> *sListArray;
/** The number of items in @c sListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sListArray_Count;

@end

#pragma mark - MEGradeList

typedef GPB_ENUM(MEGradeList_FieldNumber) {
  MEGradeList_FieldNumber_ListArray = 1,
};

@interface MEGradeList : GPBMessage

/** 年级列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEGrade*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
