// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEPhoneInfo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MephoneInfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MephoneInfoRoot : GPBRootObject
@end

#pragma mark - MEPBPhoneInfo

typedef GPB_ENUM(MEPBPhoneInfo_FieldNumber) {
  MEPBPhoneInfo_FieldNumber_DeviceId = 1,
  MEPBPhoneInfo_FieldNumber_SubscriberId = 2,
  MEPBPhoneInfo_FieldNumber_Model = 3,
  MEPBPhoneInfo_FieldNumber_Brand = 4,
  MEPBPhoneInfo_FieldNumber_Number = 5,
  MEPBPhoneInfo_FieldNumber_AppVersion = 6,
  MEPBPhoneInfo_FieldNumber_OsVersion = 7,
};

@interface MEPBPhoneInfo : GPBMessage

/** 设备id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceId;

/** 用户识别id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *subscriberId;

/** 手机型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

/** 手机品牌 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *brand;

/** 手机号码 有的可得，有的不可得 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *number;

/** app版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appVersion;

/** os版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osVersion;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
