// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESchoolAddress.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MeschoolAddress.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MeschoolAddressRoot

@implementation MeschoolAddressRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - MeschoolAddressRoot_FileDescriptor

static GPBFileDescriptor *MeschoolAddressRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - SchoolAddressListPb

@implementation SchoolAddressListPb

@dynamic keyword;
@dynamic schoolListArray, schoolListArray_Count;

typedef struct SchoolAddressListPb__storage_ {
  uint32_t _has_storage_[1];
  NSString *keyword;
  NSMutableArray *schoolListArray;
} SchoolAddressListPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "keyword",
        .dataTypeSpecific.className = NULL,
        .number = SchoolAddressListPb_FieldNumber_Keyword,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SchoolAddressListPb__storage_, keyword),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "schoolListArray",
        .dataTypeSpecific.className = GPBStringifySymbol(SchoolAddressPb),
        .number = SchoolAddressListPb_FieldNumber_SchoolListArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SchoolAddressListPb__storage_, schoolListArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SchoolAddressListPb class]
                                     rootClass:[MeschoolAddressRoot class]
                                          file:MeschoolAddressRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SchoolAddressListPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\000schoolList\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SchoolAddressPb

@implementation SchoolAddressPb

@dynamic id_p;
@dynamic name;
@dynamic provinceName;
@dynamic cityName;
@dynamic districtName;

typedef struct SchoolAddressPb__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSString *provinceName;
  NSString *cityName;
  NSString *districtName;
  int64_t id_p;
} SchoolAddressPb__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = SchoolAddressPb_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SchoolAddressPb__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = SchoolAddressPb_FieldNumber_Name,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(SchoolAddressPb__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "provinceName",
        .dataTypeSpecific.className = NULL,
        .number = SchoolAddressPb_FieldNumber_ProvinceName,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(SchoolAddressPb__storage_, provinceName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "cityName",
        .dataTypeSpecific.className = NULL,
        .number = SchoolAddressPb_FieldNumber_CityName,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(SchoolAddressPb__storage_, cityName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "districtName",
        .dataTypeSpecific.className = NULL,
        .number = SchoolAddressPb_FieldNumber_DistrictName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(SchoolAddressPb__storage_, districtName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SchoolAddressPb class]
                                     rootClass:[MeschoolAddressRoot class]
                                          file:MeschoolAddressRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SchoolAddressPb__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\003\014\000\004\010\000\005\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
