// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESchoolAddress.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SchoolAddressPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MeschoolAddressRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeschoolAddressRoot : GPBRootObject
@end

#pragma mark - SchoolAddressListPb

typedef GPB_ENUM(SchoolAddressListPb_FieldNumber) {
  SchoolAddressListPb_FieldNumber_Keyword = 1,
  SchoolAddressListPb_FieldNumber_SchoolListArray = 2,
};

@interface SchoolAddressListPb : GPBMessage

/** 查询条件关键字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SchoolAddressPb*> *schoolListArray;
/** The number of items in @c schoolListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger schoolListArray_Count;

@end

#pragma mark - SchoolAddressPb

typedef GPB_ENUM(SchoolAddressPb_FieldNumber) {
  SchoolAddressPb_FieldNumber_Id_p = 1,
  SchoolAddressPb_FieldNumber_Name = 2,
  SchoolAddressPb_FieldNumber_ProvinceName = 3,
  SchoolAddressPb_FieldNumber_CityName = 4,
  SchoolAddressPb_FieldNumber_DistrictName = 5,
};

@interface SchoolAddressPb : GPBMessage

/** 学校id */
@property(nonatomic, readwrite) int64_t id_p;

/** 学校名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 省份名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *provinceName;

/** 城市名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cityName;

/** 区县名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *districtName;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
