// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESession.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MesessionRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MesessionRoot : GPBRootObject
@end

#pragma mark - MESession

typedef GPB_ENUM(MESession_FieldNumber) {
  MESession_FieldNumber_Id_p = 1,
  MESession_FieldNumber_UserId = 2,
  MESession_FieldNumber_Type = 3,
  MESession_FieldNumber_MsId = 4,
  MESession_FieldNumber_MsName = 5,
  MESession_FieldNumber_SessionId = 6,
  MESession_FieldNumber_ModifiedDate = 7,
  MESession_FieldNumber_DataStatus = 8,
  MESession_FieldNumber_Timestamp = 9,
  MESession_FieldNumber_ReadId = 10,
  MESession_FieldNumber_LastId = 11,
};

@interface MESession : GPBMessage

/** id */
@property(nonatomic, readwrite) int64_t id_p;

/** 用户id */
@property(nonatomic, readwrite) int64_t userId;

/** 消息类型1个人信息2群组信息 */
@property(nonatomic, readwrite) int32_t type;

/** 消息源id，根据type指向不同的表 */
@property(nonatomic, readwrite) int64_t msId;

/** 姓名或群众名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *msName;

/** session id */
@property(nonatomic, readwrite) int64_t sessionId;

/** 最后更新时间 */
@property(nonatomic, readwrite) int64_t modifiedDate;

/** 数据状态 */
@property(nonatomic, readwrite) int32_t dataStatus;

/** 时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

/** 已读id */
@property(nonatomic, readwrite) int64_t readId;

/** 未读id */
@property(nonatomic, readwrite) int64_t lastId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
