// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESessionList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MECSession;
@class MECUser;
@class MESession;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MesessionListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MesessionListRoot : GPBRootObject
@end

#pragma mark - MESessionList

typedef GPB_ENUM(MESessionList_FieldNumber) {
  MESessionList_FieldNumber_MessageArray = 1,
  MESessionList_FieldNumber_ClassUserArray = 9,
  MESessionList_FieldNumber_ClassSessionArray = 10,
};

@interface MESessionList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MESession*> *messageArray;
/** The number of items in @c messageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageArray_Count;

/** 班级用户 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MECUser*> *classUserArray;
/** The number of items in @c classUserArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classUserArray_Count;

/** 班级会话 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MECSession*> *classSessionArray;
/** The number of items in @c classSessionArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classSessionArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
