// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEServerList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MESocketServer;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MeserverListRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeserverListRoot : GPBRootObject
@end

#pragma mark - MESocketServer

typedef GPB_ENUM(MESocketServer_FieldNumber) {
  MESocketServer_FieldNumber_Host = 1,
  MESocketServer_FieldNumber_Port = 2,
};

@interface MESocketServer : GPBMessage

/** 域名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *host;

/** 端口 */
@property(nonatomic, readwrite) int32_t port;

@end

#pragma mark - MEServerList

typedef GPB_ENUM(MEServerList_FieldNumber) {
  MEServerList_FieldNumber_SocketServerArray = 1,
};

@interface MEServerList : GPBMessage

/** socket服务 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MESocketServer*> *socketServerArray;
/** The number of items in @c socketServerArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger socketServerArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
