// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESemesterEvaluate.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SEEvaluateItem;
@class SEEvaluateSubType;
@class SEEvaluateType;
@class SemesterEvaluate;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MesemesterEvaluateRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MesemesterEvaluateRoot : GPBRootObject
@end

#pragma mark - SEEvaluateItem

typedef GPB_ENUM(SEEvaluateItem_FieldNumber) {
  SEEvaluateItem_FieldNumber_Id_p = 1,
  SEEvaluateItem_FieldNumber_Title = 3,
  SEEvaluateItem_FieldNumber_Answer = 4,
};

/**
 * 问题item 都是单选
 **/
@interface SEEvaluateItem : GPBMessage

/** 问题ID 全局唯一 */
@property(nonatomic, readwrite) int64_t id_p;

/** 问题描述 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 固定值： 0未选择 1做到了 2有进步 3要加油 */
@property(nonatomic, readwrite) int32_t answer;

@end

#pragma mark - SEEvaluateSubType

typedef GPB_ENUM(SEEvaluateSubType_FieldNumber) {
  SEEvaluateSubType_FieldNumber_Id_p = 1,
  SEEvaluateSubType_FieldNumber_Title = 2,
  SEEvaluateSubType_FieldNumber_ItemsArray = 3,
};

/**
 * 子类型：身心状况/动作发展
 **/
@interface SEEvaluateSubType : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 问题列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SEEvaluateItem*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - SEEvaluateType

typedef GPB_ENUM(SEEvaluateType_FieldNumber) {
  SEEvaluateType_FieldNumber_Id_p = 1,
  SEEvaluateType_FieldNumber_Title = 2,
  SEEvaluateType_FieldNumber_SubTypesArray = 3,
};

/**
 * 大类型：健康/语言/社会/科学/艺术
 **/
@interface SEEvaluateType : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 子分类列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SEEvaluateSubType*> *subTypesArray;
/** The number of items in @c subTypesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger subTypesArray_Count;

@end

#pragma mark - SemesterEvaluate

typedef GPB_ENUM(SemesterEvaluate_FieldNumber) {
  SemesterEvaluate_FieldNumber_Id_p = 1,
  SemesterEvaluate_FieldNumber_GradeId = 2,
  SemesterEvaluate_FieldNumber_Semester = 3,
  SemesterEvaluate_FieldNumber_StudentId = 4,
  SemesterEvaluate_FieldNumber_Title = 5,
  SemesterEvaluate_FieldNumber_Status = 6,
  SemesterEvaluate_FieldNumber_TypesArray = 7,
  SemesterEvaluate_FieldNumber_QuesItemsArray = 8,
};

/**
 * 学期评价 数据对接
 **/
@interface SemesterEvaluate : GPBMessage

/** ? */
@property(nonatomic, readwrite) int64_t id_p;

/** 年级 */
@property(nonatomic, readwrite) int64_t gradeId;

/** 学期 */
@property(nonatomic, readwrite) int64_t semester;

/** 学生ID */
@property(nonatomic, readwrite) int64_t studentId;

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 状态 1已完成 0未填写 2已暂存 */
@property(nonatomic, readwrite) int32_t status;

/** 大类型列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SEEvaluateType*> *typesArray;
/** The number of items in @c typesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger typesArray_Count;

/** 题目列表 暂存时使用 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SEEvaluateItem*> *quesItemsArray;
/** The number of items in @c quesItemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger quesItemsArray_Count;

@end

#pragma mark - SemesterEvaluateList

typedef GPB_ENUM(SemesterEvaluateList_FieldNumber) {
  SemesterEvaluateList_FieldNumber_EvaluatesArray = 1,
};

@interface SemesterEvaluateList : GPBMessage

/** 列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SemesterEvaluate*> *evaluatesArray;
/** The number of items in @c evaluatesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger evaluatesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
