// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESessionList.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "MesessionList.pbobjc.h"
 #import "Mesession.pbobjc.h"
 #import "MeclassChat.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MesessionListRoot

@implementation MesessionListRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MesessionListRoot_FileDescriptor

static GPBFileDescriptor *MesessionListRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - MESessionList

@implementation MESessionList

@dynamic messageArray, messageArray_Count;
@dynamic classUserArray, classUserArray_Count;
@dynamic classSessionArray, classSessionArray_Count;

typedef struct MESessionList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *messageArray;
  NSMutableArray *classUserArray;
  NSMutableArray *classSessionArray;
} MESessionList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messageArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MESession),
        .number = MESessionList_FieldNumber_MessageArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MESessionList__storage_, messageArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "classUserArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MECUser),
        .number = MESessionList_FieldNumber_ClassUserArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MESessionList__storage_, classUserArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "classSessionArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MECSession),
        .number = MESessionList_FieldNumber_ClassSessionArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MESessionList__storage_, classSessionArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MESessionList class]
                                     rootClass:[MesessionListRoot class]
                                          file:MesessionListRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MESessionList__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\t\000classUser\000\n\000classSession\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
