// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESignIn.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MesignInRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MesignInRoot : GPBRootObject
@end

#pragma mark - MEPBSignIn

typedef GPB_ENUM(MEPBSignIn_FieldNumber) {
  MEPBSignIn_FieldNumber_LoginName = 1,
  MEPBSignIn_FieldNumber_Password = 2,
  MEPBSignIn_FieldNumber_Token = 3,
  MEPBSignIn_FieldNumber_Name = 5,
  MEPBSignIn_FieldNumber_AppleToken = 6,
  MEPBSignIn_FieldNumber_Code = 7,
  MEPBSignIn_FieldNumber_ClassNo = 8,
};

@interface MEPBSignIn : GPBMessage

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginName;

/** 密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

/** token,用于记住密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 苹果deviceToken */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appleToken;

/** 手机验证码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

/** 班级编号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *classNo;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
