// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEStuFun.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GuFunPhotoImgPb;
@class GuFunPhotoPb;
@class GuFunPhotoStudentPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MestuFunRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MestuFunRoot : GPBRootObject
@end

#pragma mark - GuFunPhotoListPb

typedef GPB_ENUM(GuFunPhotoListPb_FieldNumber) {
  GuFunPhotoListPb_FieldNumber_FunPhotoPbArray = 1,
};

@interface GuFunPhotoListPb : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GuFunPhotoPb*> *funPhotoPbArray;
/** The number of items in @c funPhotoPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger funPhotoPbArray_Count;

@end

#pragma mark - GuFunPhotoPb

typedef GPB_ENUM(GuFunPhotoPb_FieldNumber) {
  GuFunPhotoPb_FieldNumber_Id_p = 1,
  GuFunPhotoPb_FieldNumber_StudentId = 2,
  GuFunPhotoPb_FieldNumber_GradeId = 3,
  GuFunPhotoPb_FieldNumber_Month = 4,
  GuFunPhotoPb_FieldNumber_Title = 5,
  GuFunPhotoPb_FieldNumber_FunText = 6,
  GuFunPhotoPb_FieldNumber_Status = 7,
  GuFunPhotoPb_FieldNumber_StudentListArray = 8,
  GuFunPhotoPb_FieldNumber_ImgListArray = 9,
  GuFunPhotoPb_FieldNumber_Type = 10,
  GuFunPhotoPb_FieldNumber_CreatedDate = 11,
  GuFunPhotoPb_FieldNumber_CreatedBy = 12,
};

@interface GuFunPhotoPb : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

/** 学生id */
@property(nonatomic, readwrite) int64_t studentId;

/** 年级id */
@property(nonatomic, readwrite) int64_t gradeId;

/** 月份 */
@property(nonatomic, readwrite) int32_t month;

/** 标题 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

/** 文字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *funText;

/** 状态 1完成 0没完成的 */
@property(nonatomic, readwrite) int32_t status;

/** 学生列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GuFunPhotoStudentPb*> *studentListArray;
/** The number of items in @c studentListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger studentListArray_Count;

/** 图片 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GuFunPhotoImgPb*> *imgListArray;
/** The number of items in @c imgListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imgListArray_Count;

/** 1幼儿园  2在家里 */
@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) int64_t createdDate;

/** 创建者 */
@property(nonatomic, readwrite) int64_t createdBy;

@end

#pragma mark - GuFunPhotoStudentPb

typedef GPB_ENUM(GuFunPhotoStudentPb_FieldNumber) {
  GuFunPhotoStudentPb_FieldNumber_StudentId = 1,
};

@interface GuFunPhotoStudentPb : GPBMessage

/** 学生id */
@property(nonatomic, readwrite) int64_t studentId;

@end

#pragma mark - GuFunPhotoImgPb

typedef GPB_ENUM(GuFunPhotoImgPb_FieldNumber) {
  GuFunPhotoImgPb_FieldNumber_ImgPath = 1,
};

@interface GuFunPhotoImgPb : GPBMessage

/** 图片路径 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imgPath;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
