// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEStudent.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MEStudent;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MestudentRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MestudentRoot : GPBRootObject
@end

#pragma mark - MEStudent

typedef GPB_ENUM(MEStudent_FieldNumber) {
  MEStudent_FieldNumber_Id_p = 1,
  MEStudent_FieldNumber_ClassId = 2,
  MEStudent_FieldNumber_Name = 3,
  MEStudent_FieldNumber_Gender = 4,
  MEStudent_FieldNumber_Portrait = 5,
  MEStudent_FieldNumber_Status = 6,
  MEStudent_FieldNumber_Prestate = 7,
};

@interface MEStudent : GPBMessage

/** 学生ID */
@property(nonatomic, readwrite) int64_t id_p;

/** 班级ID */
@property(nonatomic, readwrite) int64_t classId;

/** 中文名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 性别 */
@property(nonatomic, readwrite) int32_t gender;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

/** 1已完成 0未填写 2已暂存 */
@property(nonatomic, readwrite) int32_t status;

/** 与status相同 保存选中之前的状态 */
@property(nonatomic, readwrite) int32_t prestate;

@end

#pragma mark - MEStudentList

typedef GPB_ENUM(MEStudentList_FieldNumber) {
  MEStudentList_FieldNumber_StudentsArray = 1,
};

@interface MEStudentList : GPBMessage

/** 学生列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEStudent*> *studentsArray;
/** The number of items in @c studentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger studentsArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
