// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEUser.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class DeanPb;
@class FuncCtrlPb;
@class MEPBClass;
@class MEPBUser;
@class ParentsPb;
@class SchoolPb;
@class StudentPb;
@class SystemConfigPb;
@class TeacherPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum MEPBUserRole

typedef GPB_ENUM(MEPBUserRole) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  MEPBUserRole_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 游客 */
  MEPBUserRole_Visitor = 0,

  /** 老师 */
  MEPBUserRole_Teacher = 1,

  /** 家长 */
  MEPBUserRole_Parent = 2,

  /** 园务 */
  MEPBUserRole_Gardener = 3,
};

GPBEnumDescriptor *MEPBUserRole_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL MEPBUserRole_IsValidValue(int32_t value);

#pragma mark - MeuserRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeuserRoot : GPBRootObject
@end

#pragma mark - MEPBUserList

typedef GPB_ENUM(MEPBUserList_FieldNumber) {
  MEPBUserList_FieldNumber_UserListArray = 1,
};

@interface MEPBUserList : GPBMessage

/** 用户列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEPBUser*> *userListArray;
/** The number of items in @c userListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userListArray_Count;

@end

#pragma mark - MEPBUser

typedef GPB_ENUM(MEPBUser_FieldNumber) {
  MEPBUser_FieldNumber_Id_p = 1,
  MEPBUser_FieldNumber_SchoolId = 2,
  MEPBUser_FieldNumber_Uuid = 3,
  MEPBUser_FieldNumber_Username = 4,
  MEPBUser_FieldNumber_Password = 5,
  MEPBUser_FieldNumber_Name = 6,
  MEPBUser_FieldNumber_UserType = 7,
  MEPBUser_FieldNumber_PhaseId = 8,
  MEPBUser_FieldNumber_Gender = 9,
  MEPBUser_FieldNumber_Mobile = 10,
  MEPBUser_FieldNumber_Address = 11,
  MEPBUser_FieldNumber_Email = 12,
  MEPBUser_FieldNumber_Token = 13,
  MEPBUser_FieldNumber_SchoolName = 14,
  MEPBUser_FieldNumber_Portrait = 15,
  MEPBUser_FieldNumber_ParentsPb = 16,
  MEPBUser_FieldNumber_TeacherPb = 17,
  MEPBUser_FieldNumber_SchoolPb = 18,
  MEPBUser_FieldNumber_FuncCtrlPbArray = 19,
  MEPBUser_FieldNumber_HasInitPwd = 20,
  MEPBUser_FieldNumber_BucketDomain = 21,
  MEPBUser_FieldNumber_Uptoken = 22,
  MEPBUser_FieldNumber_GroupStatus = 23,
  MEPBUser_FieldNumber_IsMember = 24,
  MEPBUser_FieldNumber_Deadline = 25,
  MEPBUser_FieldNumber_SystemConfigPb = 26,
  MEPBUser_FieldNumber_DiskCap = 27,
  MEPBUser_FieldNumber_DeanPb = 28,
  MEPBUser_FieldNumber_IsTourist = 29,
  MEPBUser_FieldNumber_RcToken = 30,
  MEPBUser_FieldNumber_IsUserCharge = 31,
  MEPBUser_FieldNumber_Code = 32,
  MEPBUser_FieldNumber_SessionToken = 33,
  MEPBUser_FieldNumber_Signinstamp = 34,
};

@interface MEPBUser : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) int64_t id_p;

/** 学校id */
@property(nonatomic, readwrite) int64_t schoolId;

/** 唯一统一标示符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

/** 中文名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 用户类型(1老师;2学生;3家长;4教务) */
@property(nonatomic, readwrite) MEPBUserRole userType;

/** 学段id */
@property(nonatomic, readwrite) int64_t phaseId;

/** 性别1:男，2：女 */
@property(nonatomic, readwrite) int32_t gender;

/** 电话 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/** 地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

/** email */
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

/** token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** 学校名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *schoolName;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

@property(nonatomic, readwrite, strong, null_resettable) ParentsPb *parentsPb;
/** Test to see if @c parentsPb has been set. */
@property(nonatomic, readwrite) BOOL hasParentsPb;

@property(nonatomic, readwrite, strong, null_resettable) TeacherPb *teacherPb;
/** Test to see if @c teacherPb has been set. */
@property(nonatomic, readwrite) BOOL hasTeacherPb;

@property(nonatomic, readwrite, strong, null_resettable) SchoolPb *schoolPb;
/** Test to see if @c schoolPb has been set. */
@property(nonatomic, readwrite) BOOL hasSchoolPb;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FuncCtrlPb*> *funcCtrlPbArray;
/** The number of items in @c funcCtrlPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger funcCtrlPbArray_Count;

@property(nonatomic, readwrite) int32_t hasInitPwd;

/** 七牛域名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *bucketDomain;

/** 七牛上传token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uptoken;

/** 群聊开关状态 */
@property(nonatomic, readwrite) int32_t groupStatus;

/** 是否是会员 */
@property(nonatomic, readwrite) int32_t isMember;

/** 会员截止日期 */
@property(nonatomic, readwrite) int64_t deadline;

/** 系统配置 */
@property(nonatomic, readwrite, strong, null_resettable) SystemConfigPb *systemConfigPb;
/** Test to see if @c systemConfigPb has been set. */
@property(nonatomic, readwrite) BOOL hasSystemConfigPb;

/** 当前网盘容量 */
@property(nonatomic, readwrite) int64_t diskCap;

@property(nonatomic, readwrite, strong, null_resettable) DeanPb *deanPb;
/** Test to see if @c deanPb has been set. */
@property(nonatomic, readwrite) BOOL hasDeanPb;

/** 是否是游客 */
@property(nonatomic, readwrite) int32_t isTourist;

/** 融云token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *rcToken;

/** 判断用户是否需要进入收费页面 */
@property(nonatomic, readwrite) int32_t isUserCharge;

/** 验证码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

/** 用户登录后授权token */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionToken;

/** 登录时间戳 */
@property(nonatomic, readwrite) int64_t signinstamp;

@end

/**
 * Fetches the raw value of a @c MEPBUser's @c userType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t MEPBUser_UserType_RawValue(MEPBUser *message);
/**
 * Sets the raw value of an @c MEPBUser's @c userType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetMEPBUser_UserType_RawValue(MEPBUser *message, int32_t value);

#pragma mark - SchoolPb

typedef GPB_ENUM(SchoolPb_FieldNumber) {
  SchoolPb_FieldNumber_Id_p = 1,
  SchoolPb_FieldNumber_Domain = 2,
  SchoolPb_FieldNumber_Name = 3,
  SchoolPb_FieldNumber_Year = 4,
  SchoolPb_FieldNumber_Semester = 5,
  SchoolPb_FieldNumber_IsSchoolCharge = 6,
  SchoolPb_FieldNumber_FreeDate = 7,
};

@interface SchoolPb : GPBMessage

/** 学校id */
@property(nonatomic, readwrite) int64_t id_p;

/** 学校域名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *domain;

/** 学校名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 年 */
@property(nonatomic, readwrite) int64_t year;

/** 学期 */
@property(nonatomic, readwrite) int32_t semester;

/** 是否收费 */
@property(nonatomic, readwrite) int32_t isSchoolCharge;

/** 免费时间 */
@property(nonatomic, readwrite) int64_t freeDate;

@end

#pragma mark - FuncCtrlPb

typedef GPB_ENUM(FuncCtrlPb_FieldNumber) {
  FuncCtrlPb_FieldNumber_SchoolId = 1,
  FuncCtrlPb_FieldNumber_FuncCode = 2,
  FuncCtrlPb_FieldNumber_AndroidStatus = 3,
  FuncCtrlPb_FieldNumber_IosStatus = 4,
};

@interface FuncCtrlPb : GPBMessage

/** 学校id */
@property(nonatomic, readwrite) int64_t schoolId;

/** 功能code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *funcCode;

/** 状态 */
@property(nonatomic, readwrite) int32_t androidStatus;

/** 状态 */
@property(nonatomic, readwrite) int32_t iosStatus;

@end

#pragma mark - ParentsPb

typedef GPB_ENUM(ParentsPb_FieldNumber) {
  ParentsPb_FieldNumber_Mobile = 1,
  ParentsPb_FieldNumber_StudentPbArray = 2,
  ParentsPb_FieldNumber_ClassPbArray = 3,
  ParentsPb_FieldNumber_CutStudenId = 4,
};

@interface ParentsPb : GPBMessage

/** 手机 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/** 学生列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<StudentPb*> *studentPbArray;
/** The number of items in @c studentPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger studentPbArray_Count;

/** 学生班级 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEPBClass*> *classPbArray;
/** The number of items in @c classPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classPbArray_Count;

/** 当前学生ID */
@property(nonatomic, readwrite) int64_t cutStudenId;

@end

#pragma mark - TeacherPb

typedef GPB_ENUM(TeacherPb_FieldNumber) {
  TeacherPb_FieldNumber_Mobile = 1,
  TeacherPb_FieldNumber_ClassPbArray = 2,
};

@interface TeacherPb : GPBMessage

/** 手机 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/** 班级 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEPBClass*> *classPbArray;
/** The number of items in @c classPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classPbArray_Count;

@end

#pragma mark - DeanPb

typedef GPB_ENUM(DeanPb_FieldNumber) {
  DeanPb_FieldNumber_ClassPbArray = 1,
};

@interface DeanPb : GPBMessage

/** 班级 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MEPBClass*> *classPbArray;
/** The number of items in @c classPbArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger classPbArray_Count;

@end

#pragma mark - StudentPb

typedef GPB_ENUM(StudentPb_FieldNumber) {
  StudentPb_FieldNumber_Id_p = 1,
  StudentPb_FieldNumber_Uuid = 2,
  StudentPb_FieldNumber_Name = 3,
  StudentPb_FieldNumber_ClassId = 4,
  StudentPb_FieldNumber_GradeId = 5,
  StudentPb_FieldNumber_ClassNo = 6,
  StudentPb_FieldNumber_Birthday = 7,
  StudentPb_FieldNumber_ParentType = 8,
  StudentPb_FieldNumber_Gender = 9,
};

@interface StudentPb : GPBMessage

@property(nonatomic, readwrite) int64_t id_p;

/** 唯一统一标示符 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uuid;

/** 名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 班级 */
@property(nonatomic, readwrite) int64_t classId;

/** 年级 */
@property(nonatomic, readwrite) int64_t gradeId;

/** 班级码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *classNo;

/** 出生日期 */
@property(nonatomic, readwrite) int64_t birthday;

/** 家长类型 */
@property(nonatomic, readwrite) int32_t parentType;

/** 性别 */
@property(nonatomic, readwrite) int32_t gender;

@end

#pragma mark - SystemConfigPb

typedef GPB_ENUM(SystemConfigPb_FieldNumber) {
  SystemConfigPb_FieldNumber_DiskCap = 1,
  SystemConfigPb_FieldNumber_UploadLimit = 2,
};

@interface SystemConfigPb : GPBMessage

/** 网盘容量 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *diskCap;

/** 上传限制 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *uploadLimit;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
