// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MEUserData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FscUserPb;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MeuserDataRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MeuserDataRoot : GPBRootObject
@end

#pragma mark - FscUserPbList

typedef GPB_ENUM(FscUserPbList_FieldNumber) {
  FscUserPbList_FieldNumber_FscUserPb = 1,
};

@interface FscUserPbList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) FscUserPb *fscUserPb;
/** Test to see if @c fscUserPb has been set. */
@property(nonatomic, readwrite) BOOL hasFscUserPb;

@end

#pragma mark - FscUserPb

typedef GPB_ENUM(FscUserPb_FieldNumber) {
  FscUserPb_FieldNumber_Id_p = 1,
  FscUserPb_FieldNumber_Username = 2,
  FscUserPb_FieldNumber_Password = 3,
  FscUserPb_FieldNumber_Name = 4,
  FscUserPb_FieldNumber_Gender = 5,
  FscUserPb_FieldNumber_Mobile = 6,
  FscUserPb_FieldNumber_UserType = 7,
  FscUserPb_FieldNumber_Portrait = 8,
  FscUserPb_FieldNumber_SchoolName = 9,
  FscUserPb_FieldNumber_Keyword = 10,
  FscUserPb_FieldNumber_LinkmanId = 11,
  FscUserPb_FieldNumber_AddStatus = 12,
  FscUserPb_FieldNumber_ClassId = 13,
  FscUserPb_FieldNumber_Code = 14,
  FscUserPb_FieldNumber_QqUid = 15,
  FscUserPb_FieldNumber_WxUid = 16,
  FscUserPb_FieldNumber_DiskCap = 17,
  FscUserPb_FieldNumber_SessionToken = 18,
  FscUserPb_FieldNumber_Repassword = 19,
};

@interface FscUserPb : GPBMessage

/** 用户id */
@property(nonatomic, readwrite) int64_t id_p;

/** 用户名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

/** 密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

/** 中文名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 性别1:男，2：女 */
@property(nonatomic, readwrite) int32_t gender;

/** 手机号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

/** 用户类型(1老师;2学生;3家长;4教务) */
@property(nonatomic, readwrite) int32_t userType;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *portrait;

/** 学校名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *schoolName;

/** 查询条件 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

/** 添加的联系人id */
@property(nonatomic, readwrite) int64_t linkmanId;

/** 添加的联系人状态(1申请2同意3拒绝) */
@property(nonatomic, readwrite) int32_t addStatus;

/** 班级id */
@property(nonatomic, readwrite) int64_t classId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *qqUid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *wxUid;

/** 当前网盘容量 */
@property(nonatomic, readwrite) int64_t diskCap;

/** sessionToken */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionToken;

/** 旧密码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *repassword;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
